version: "3"
services:
    web:
        build: ./web
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        environment:
            FLASK_ENV: development
        links:
            - db
    db:
        build: ./db
